import { inter } from "@/app/ui/fonts";
import "@/app/ui/global.css";
import Navbar from "@/components/navbar/page";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  icons: {
    icon: "/assets/images/logos/logo-no-background-scaled.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Navbar className="bg-opacity-80"/>
        {children}
      </body>
    </html>
  );
}
