export const recipe = {
  id: 1,
  name: "Homemade Margherita Pizza",
  description:
    "Classic Italian pizza with fresh basil, mozzarella, and tomatoes",
  image: "/assets/images/landing/img-2.jpg",
  tags: ["Italian", "Vegetarian", "Dinner", "Baking"],
  difficulty: "Medium",
  time: "45 mins",
  servings: 4,
  ingredients: [
    "2 1/4 cups (280g) all-purpose flour",
    "1 cup (240ml) warm water",
    "2 1/4 tsp active dry yeast",
    "1 tbsp olive oil",
    "1 tsp salt",
    "Fresh mozzarella",
    "Fresh basil leaves",
    "San Marzano tomatoes",
    "Extra virgin olive oil",
  ],
  instructions: [
    "Mix warm water with yeast and let stand for 5 minutes",
    "Combine flour and salt in a large bowl",
    "Add olive oil and yeast mixture to flour",
    "Knead dough for 10 minutes until smooth",
    "Let rise for 1 hour in a warm place",
    "Preheat oven to 500°F (260°C)",
    "Roll out dough and add toppings",
    "Bake for 12-15 minutes until crust is golden",
  ],
};
