export const recipes = [
  {
    id: 1,
    name: "Spicy Pepperoni Pizza",
    description: "A zesty pizza topped with pepperoni and chili flakes.",
    image: "/assets/images/landing/img-2.jpg",
    tags: ["Italian", "Spicy", "Dinner", "Cheesy"],
    difficulty: "Medium",
    time: "40 mins",
    servings: 4,
    ingredients: [
      "Pizza dough",
      "Tomato sauce",
      "Pepperoni slices",
      "Mozzarella cheese",
      "Chili flakes",
      "Olive oil",
    ],
    instructions: [
      "Preheat oven to 450°F (230°C).",
      "Spread tomato sauce over the dough.",
      "Add mozzarella cheese and pepperoni slices.",
      "Sprinkle chili flakes and drizzle olive oil.",
      "Bake for 12-15 minutes until crust is golden.",
    ],
    price: { base: 18 },
    prep_time: "15 minutes",
    nutritional_info: {
      calories: 1200,
      protein: 15,
      fat: 25,
      carbohydrates: 35,
    },
    availability: {
      lead_time: "1 hour",
    },
  },
  {
    id: 2,
    name: "Veggie Supreme Pizza",
    description: "A colorful pizza loaded with fresh vegetables.",
    image: "/assets/images/landing/img-2.jpg",
    tags: ["Italian", "Vegetarian", "Healthy", "Dinner"],
    difficulty: "Easy",
    time: "35 mins",
    servings: 4,
    ingredients: [
      "Pizza dough",
      "Tomato sauce",
      "Bell peppers",
      "Onions",
      "Mushrooms",
      "Olives",
      "Mozzarella cheese",
    ],
    instructions: [
      "Preheat oven to 450°F (230°C).",
      "Spread tomato sauce over the dough.",
      "Add mozzarella cheese and assorted vegetables.",
      "Bake for 12-15 minutes until vegetables are tender.",
    ],
    price: { base: 16 },
    prep_time: "20 minutes",
    nutritional_info: {
      calories: 1100,
      protein: 10,
      fat: 15,
      carbohydrates: 40,
    },
    availability: {
      lead_time: "45 minutes",
    },
  },
  {
    id: 3,
    name: "BBQ Chicken Pizza",
    description: "A smoky delight topped with BBQ sauce and chicken.",
    image: "/assets/images/landing/img-2.jpg",
    tags: ["Italian", "BBQ", "Chicken", "Cheesy"],
    difficulty: "Medium",
    time: "45 mins",
    servings: 4,
    ingredients: [
      "Pizza dough",
      "BBQ sauce",
      "Grilled chicken strips",
      "Mozzarella cheese",
      "Red onions",
      "Cilantro",
    ],
    instructions: [
      "Preheat oven to 450°F (230°C).",
      "Spread BBQ sauce over the dough.",
      "Add mozzarella cheese, chicken strips, and red onions.",
      "Bake for 12-15 minutes until crust is golden.",
      "Garnish with fresh cilantro.",
    ],
    price: { base: 20 },
    prep_time: "25 minutes",
    nutritional_info: {
      calories: 1300,
      protein: 20,
      fat: 30,
      carbohydrates: 50,
    },
    availability: {
      lead_time: "1 hour",
    },
  },
  {
    id: 4,
    name: "Hawaiian Pizza",
    description: "A sweet and savory pizza with ham and pineapple.",
    image: "/assets/images/landing/img-2.jpg",
    tags: ["Italian", "Sweet", "Dinner", "Cheesy"],
    difficulty: "Easy",
    time: "30 mins",
    servings: 4,
    ingredients: [
      "Pizza dough",
      "Tomato sauce",
      "Ham slices",
      "Pineapple chunks",
      "Mozzarella cheese",
    ],
    instructions: [
      "Preheat oven to 450°F (230°C).",
      "Spread tomato sauce over the dough.",
      "Add mozzarella cheese, ham slices, and pineapple chunks.",
      "Bake for 12-15 minutes until cheese is bubbly.",
    ],
    price: { base: 17 },
    prep_time: "15 minutes",
    nutritional_info: {
      calories: 1150,
      protein: 18,
      fat: 20,
      carbohydrates: 35,
    },
    availability: {
      lead_time: "30 minutes",
    },
  },
  {
    id: 5,
    name: "Truffle Mushroom Pizza",
    description: "A gourmet pizza with truffle oil and mushrooms.",
    image: "/assets/images/landing/img-2.jpg",
    tags: ["Italian", "Gourmet", "Vegetarian", "Dinner"],
    difficulty: "Hard",
    time: "50 mins",
    servings: 4,
    ingredients: [
      "Pizza dough",
      "White sauce",
      "Mushrooms",
      "Mozzarella cheese",
      "Parmesan cheese",
      "Truffle oil",
    ],
    instructions: [
      "Preheat oven to 450°F (230°C).",
      "Spread white sauce over the dough.",
      "Add mozzarella and parmesan cheese, and mushrooms.",
      "Drizzle with truffle oil before baking.",
      "Bake for 12-15 minutes until crust is golden.",
    ],
    price: { base: 25 },
    prep_time: "30 minutes",
    nutritional_info: {
      calories: 1400,
      protein: 12,
      fat: 35,
      carbohydrates: 30,
    },
    availability: {
      lead_time: "1.5 hours",
    },
  },
];
